# databases:
  # - name: mysite
    # databaseName: mysite
    # user: mysite

services:
  - type: web
    # name: mysite
    name: rails
    # plan: free
    # env: ruby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    # startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      # - key: DATABASE_URL
        # fromDatabase:
          # name: mysite
          # property: connectionString
  # - type: redis
    # name: redis
    # ipAllowList: []
    # plan: free
    # maxmemoryPolicy: noeviction